# Generated by Django 5.1.4 on 2025-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
