# Generated by Django 5.1.4 on 2024-12-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=2000)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
