#name: Deploy to EC2
#
#on:
#  push:
#    branches:
#      - dev
#  pull_request:
#    branches:
#      - dev
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Python environment
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.13
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run tests
#        run: python manage.py test
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Copy .env to EC2
#        uses: appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          source: ".github/workflows/.env"
#          target: "/home/${{ secrets.EC2_USER }}/app/.env"
#
#      - name: SSH into EC2 and Deploy
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            cd /home/${{ secrets.EC2_USER }}/app
#            echo "${{ secrets.SECRET_KEY }}" > .env
#            echo "${{ secrets.DEBUG }}" >> .env
#            echo "${{ secrets.DB_NAME }}" >> .env
#            echo "${{ secrets.DB_USER }}" >> .env
#            echo "${{ secrets.DB_PASSWORD }}" >> .env
#            echo "${{ secrets.DB_HOST }}" >> .env
#            echo "${{ secrets.DB_PORT }}" >> .env
#            echo "${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
#            echo "${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
#            echo "${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
#            echo "${{ secrets.EMAIL_HOST_USER }}" >> .env
#            echo "${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
#            echo "${{ secrets.OPENAI_API_KEY }}" >> .env
#            echo "${{ secrets.OPENAI_BASE_URL }}" >> .env
#            echo "${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
#            echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
#            echo "${{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> .env
#            echo "${{ secrets.AWS_S3_REGION_NAME }}" >> .env
#
#            docker-compose down
#            docker-compose up --build -d
